### ISSUE TITLE
should probably update the README...

### ISSUE THREAD

**Issue by VerODyne** [jbbarth/redmine_better_crossprojects#11]
I just installed on 2.6.9 and it works fine. The warning about <= 2.3 can probably be removed. Now what about 3.x possibilities? :)

[And no, I have not looked at 3.anything yet to know if this would even be of benefit...]

**Comment by nanego** [comment]
We are currently using this plugin with Redmine 3.2.3.
So we should definitely update the README. Thank you ;)

**Comment by nanego** [comment]
README file has been updated. Thx.
