### ISSUE TITLE
How is the data in the table uptaded?

### ISSUE THREAD

**Issue by tantic** [jbbarth/redmine_better_crossprojects#16]
Hello,

first of all thanks very much for this plugin this is exactly what I was looking for.

I installed it on a local environment and before installing it on other environments, i would like to know how the data are updated in the table especially the columns "activity", "demand" and "users".
I added some users and demands in a project but this datas don't get updated. 
Here is a screenshot of my project in the table

![capture du 2018-10-23 13-40-14](https://user-images.githubusercontent.com/22457774/47358314-b815b100-d6c9-11e8-8be0-3af6146afb4d.png)

But on another environment I managed to have values on those columns so I don't understand how it works. Is there any cron or something to set?

**Comment by nanego** [comment]
Hello
The plugin uses a caching strategy in order to improve performances.
Columns Activity, Issues and Users are updated only once per day (at midnight) or when a new project is created.
Glad to know this plugin is useful for you.

**Comment by tantic** [comment]
Great, ok thanks! 
I was wondering if it could be a problem with lot's of projects but this seems to be a good solution.
Is there a mechanism to update this manually on demand or to flush the cache?

**Comment by nanego** [comment]
Sure. You can use Rails.cache.clear to flush cache files.

**Comment by tantic** [comment]
ok cool, thanks very much!
